// <auto-generated />
using System;
using FundRecommendationAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FundRecommendationAPI.Migrations
{
    [DbContext(typeof(FundDbContext))]
    partial class FundDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("FundRecommendationAPI.Models.FundAssetScale", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("code");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT")
                        .HasColumnName("date");

                    b.Property<decimal>("AssetScale")
                        .HasColumnType("DECIMAL(12,2)")
                        .HasColumnName("asset_scale");

                    b.Property<decimal>("ShareScale")
                        .HasColumnType("DECIMAL(12,2)")
                        .HasColumnName("share_scale");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("update_time");

                    b.HasKey("Code", "Date");

                    b.HasIndex("Code", "Date")
                        .IsUnique();

                    b.ToTable("fund_asset_scale");
                });

            modelBuilder.Entity("FundRecommendationAPI.Models.FundBasicInfo", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("code");

                    b.Property<string>("Benchmark")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("benchmark");

                    b.Property<string>("Custodian")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("custodian");

                    b.Property<decimal>("CustodianFeeRate")
                        .HasColumnType("DECIMAL(5,4)")
                        .HasColumnName("custodian_fee_rate");

                    b.Property<DateOnly>("EstablishDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("establish_date");

                    b.Property<string>("FundType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("fund_type");

                    b.Property<string>("InvestmentStyle")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("investment_style");

                    b.Property<DateOnly?>("ListDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("list_date");

                    b.Property<string>("MainFundCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("main_fund_code");

                    b.Property<decimal>("ManagementFeeRate")
                        .HasColumnType("DECIMAL(5,4)")
                        .HasColumnName("management_fee_rate");

                    b.Property<string>("Manager")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("manager");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("RiskLevel")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT")
                        .HasColumnName("risk_level");

                    b.Property<decimal?>("SalesFeeRate")
                        .HasColumnType("DECIMAL(5,4)")
                        .HasColumnName("sales_fee_rate");

                    b.Property<string>("ShareType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT")
                        .HasColumnName("share_type");

                    b.Property<string>("TrackingTarget")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("tracking_target");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("update_time");

                    b.HasKey("Code");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("FundType");

                    b.HasIndex("Manager");

                    b.HasIndex("RiskLevel");

                    b.ToTable("fund_basic_info");
                });

            modelBuilder.Entity("FundRecommendationAPI.Models.FundCorporateActions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateOnly?>("AnnouncementDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("announcement_date");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("code");

                    b.Property<decimal?>("DividendPerShare")
                        .HasColumnType("DECIMAL(10,4)")
                        .HasColumnName("dividend_per_share");

                    b.Property<string>("EventDescription")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("event_description");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("event_type");

                    b.Property<DateOnly>("ExDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("ex_date");

                    b.Property<DateOnly?>("PaymentDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("payment_date");

                    b.Property<DateOnly?>("RecordDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("record_date");

                    b.Property<decimal?>("SplitRatio")
                        .HasColumnType("DECIMAL(10,4)")
                        .HasColumnName("split_ratio");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("update_time");

                    b.HasKey("Id");

                    b.HasIndex("EventType");

                    b.HasIndex("Code", "ExDate");

                    b.ToTable("fund_corporate_actions");
                });

            modelBuilder.Entity("FundRecommendationAPI.Models.FundManager", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("code");

                    b.Property<string>("ManagerName")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("manager_name");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("start_date");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("end_date");

                    b.Property<int>("ManageDays")
                        .HasColumnType("INTEGER")
                        .HasColumnName("manage_days");

                    b.Property<decimal>("Tenure")
                        .HasColumnType("DECIMAL(5,1)")
                        .HasColumnName("tenure");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("update_time");

                    b.HasKey("Code", "ManagerName", "StartDate");

                    b.HasIndex("Code");

                    b.ToTable("fund_manager");
                });

            modelBuilder.Entity("FundRecommendationAPI.Models.FundNavHistory", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("code");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT")
                        .HasColumnName("date");

                    b.Property<decimal>("AccumulatedNav")
                        .HasColumnType("DECIMAL(10,4)")
                        .HasColumnName("accumulated_nav");

                    b.Property<decimal?>("DailyGrowthRate")
                        .HasColumnType("DECIMAL(8,4)")
                        .HasColumnName("daily_growth_rate");

                    b.Property<decimal>("Nav")
                        .HasColumnType("DECIMAL(10,4)")
                        .HasColumnName("nav");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("update_time");

                    b.HasKey("Code", "Date");

                    b.HasIndex("Date");

                    b.HasIndex("Code", "Date")
                        .IsUnique();

                    b.ToTable("fund_nav_history");
                });

            modelBuilder.Entity("FundRecommendationAPI.Models.FundPerformance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<decimal?>("AnnualReturn")
                        .HasColumnType("DECIMAL(8,4)")
                        .HasColumnName("annual_return");

                    b.Property<decimal?>("CalmarRatio")
                        .HasColumnType("DECIMAL(8,4)")
                        .HasColumnName("calmar_ratio");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("code");

                    b.Property<decimal?>("DownsideStd")
                        .HasColumnType("DECIMAL(8,4)")
                        .HasColumnName("downside_std");

                    b.Property<decimal?>("MaxDrawdown")
                        .HasColumnType("DECIMAL(8,4)")
                        .HasColumnName("max_drawdown");

                    b.Property<decimal>("NavGrowthRate")
                        .HasColumnType("DECIMAL(8,4)")
                        .HasColumnName("nav_growth_rate");

                    b.Property<string>("PeriodType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("period_type");

                    b.Property<string>("PeriodValue")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("period_value");

                    b.Property<int?>("RankInCategory")
                        .HasColumnType("INTEGER")
                        .HasColumnName("rank_in_category");

                    b.Property<decimal?>("SharpeRatio")
                        .HasColumnType("DECIMAL(8,4)")
                        .HasColumnName("sharpe_ratio");

                    b.Property<decimal?>("SortinoRatio")
                        .HasColumnType("DECIMAL(8,4)")
                        .HasColumnName("sortino_ratio");

                    b.Property<int?>("TotalInCategory")
                        .HasColumnType("INTEGER")
                        .HasColumnName("total_in_category");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("update_time");

                    b.Property<decimal?>("Volatility")
                        .HasColumnType("DECIMAL(8,4)")
                        .HasColumnName("volatility");

                    b.HasKey("Id");

                    b.HasIndex("Code", "PeriodType")
                        .IsUnique();

                    b.HasIndex("PeriodType", "Code", "NavGrowthRate");

                    b.ToTable("fund_performance");
                });

            modelBuilder.Entity("FundRecommendationAPI.Models.FundPurchaseStatus", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("code");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT")
                        .HasColumnName("date");

                    b.Property<decimal?>("PurchaseFeeRate")
                        .HasColumnType("DECIMAL(5,4)")
                        .HasColumnName("purchase_fee_rate");

                    b.Property<decimal?>("PurchaseLimit")
                        .HasColumnType("DECIMAL(12,2)")
                        .HasColumnName("purchase_limit");

                    b.Property<string>("PurchaseStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("purchase_status");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("update_time");

                    b.HasKey("Code", "Date");

                    b.HasIndex("Code", "Date")
                        .IsUnique();

                    b.ToTable("fund_purchase_status");
                });

            modelBuilder.Entity("FundRecommendationAPI.Models.FundRedemptionStatus", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("code");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT")
                        .HasColumnName("date");

                    b.Property<decimal?>("RedemptionFeeRate")
                        .HasColumnType("DECIMAL(5,4)")
                        .HasColumnName("redemption_fee_rate");

                    b.Property<decimal?>("RedemptionLimit")
                        .HasColumnType("DECIMAL(12,2)")
                        .HasColumnName("redemption_limit");

                    b.Property<string>("RedemptionStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("redemption_status");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("update_time");

                    b.HasKey("Code", "Date");

                    b.HasIndex("Code", "Date")
                        .IsUnique();

                    b.ToTable("fund_redemption_status");
                });

            modelBuilder.Entity("FundRecommendationAPI.Models.SystemUpdateHistory", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<int>("RecordsUpdated")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Status");

                    b.ToTable("SystemUpdateHistory");
                });

            modelBuilder.Entity("FundRecommendationAPI.Models.UserFavoriteFunds", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("AddTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("add_time");

                    b.Property<string>("AlertSettings")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("alert_settings");

                    b.Property<string>("FundCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("fund_code");

                    b.Property<string>("GroupTag")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("group_tag");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("note");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER")
                        .HasColumnName("sort_order");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("update_time");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "FundCode")
                        .IsUnique();

                    b.ToTable("user_favorite_funds");
                });

            modelBuilder.Entity("FundRecommendationAPI.Models.UserFavoriteScores", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CalculateTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("calculate_time");

                    b.Property<string>("FundCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("fund_code");

                    b.Property<decimal>("RankScore")
                        .HasColumnType("DECIMAL(5,2)")
                        .HasColumnName("rank_score");

                    b.Property<decimal>("ReturnScore")
                        .HasColumnType("DECIMAL(5,2)")
                        .HasColumnName("return_score");

                    b.Property<decimal>("RiskAdjustedReturnScore")
                        .HasColumnType("DECIMAL(5,2)")
                        .HasColumnName("risk_adjusted_return_score");

                    b.Property<decimal>("RiskScore")
                        .HasColumnType("DECIMAL(5,2)")
                        .HasColumnName("risk_score");

                    b.Property<decimal?>("ScoreChange")
                        .HasColumnType("DECIMAL(5,2)")
                        .HasColumnName("score_change");

                    b.Property<DateOnly>("ScoreDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("score_date");

                    b.Property<string>("ScoreTrend")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT")
                        .HasColumnName("score_trend");

                    b.Property<decimal>("TotalScore")
                        .HasColumnType("DECIMAL(5,2)")
                        .HasColumnName("total_score");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("update_time");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("user_id");

                    b.Property<string>("WeightConfig")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("weight_config");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "FundCode", "ScoreDate")
                        .IsUnique();

                    b.ToTable("user_favorite_scores");
                });

            modelBuilder.Entity("FundRecommendationAPI.Models.FundNavHistory", b =>
                {
                    b.HasOne("FundRecommendationAPI.Models.FundBasicInfo", "Fund")
                        .WithMany("NavHistories")
                        .HasForeignKey("Code")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fund");
                });

            modelBuilder.Entity("FundRecommendationAPI.Models.FundPerformance", b =>
                {
                    b.HasOne("FundRecommendationAPI.Models.FundBasicInfo", "Fund")
                        .WithMany("Performances")
                        .HasForeignKey("Code")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fund");
                });

            modelBuilder.Entity("FundRecommendationAPI.Models.FundBasicInfo", b =>
                {
                    b.Navigation("NavHistories");

                    b.Navigation("Performances");
                });
#pragma warning restore 612, 618
        }
    }
}
